otp:
  server-url: ${SERVER_URL}
  resources:
    mail:
      mailgun:
        api-key: ${MAILGUN_API_KEY}
        domain: ${MAILGUN_DOMAIN}
    persistence:
      redis:
        url: ${REDISCLOUD_URL}
    queue:
      rabbitmq:
        url: ${CLOUDAMQP_URL}
    sms:
      mtn:
        consumer-key: ${MTN_CONSUMER_KEY}
        consumer-secret: ${MTN_CONSUMER_SECRET}
        service-code: ${MTN_SERVICE_CODE}
