otp:
  server-url: ${SERVER_URL}
  resources:
    mail:
      mailgun:
        api-key: ${MAILGUN_API_KEY}
        domain: ${MAILGUN_DOMAIN}
    persistence:
      redis:
        url: ${REDISCLOUD_URL}
    queue:
      rabbitmq:
        url: ${CLOUDAMQP_URL}
