spring:
  jackson:
    read:
      ALLOW_UNESCAPED_CONTROL_CHARS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
    configprops:
      enabled: true
      show-values: always

  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks,mappings"

logging:
  level:
    root: INFO
    com.pragmaticnerdz: DEBUG
    springfox: ERROR

  pattern:
    console: "%d Type=%level Logger=%c Thread=%thread %m%n"
    file: "%d Type=%level Logger=%c Thread=%thread %m%n"

otp:
  server-url: http://localhost:8080
  resources:
    persistence:
      redis:
        url: redis://localhost:6379
    queue:
      rabbitmq:
        url: amqp://localhost
    mail:
      mailgun:
        api-key: "---"
        domain: "domain"
