name: pull_request

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    # -- SETUP --------------------------------------------------------------------
    #
    # Setup the services needed to build the app
    #  - redis
    #  - rabbitmq
    #
    # -----------------------------------------------------------------------------
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672

    steps:
      # -- BUILD -------------------------------------------------------------------------------
      #
      # Build the app:
      #  - Checkout the code
      #  - Install JDK
      #  - Build the code using Maven
      #
      # ---------------------------------------------------------------------------------------
      - uses: actions/checkout@v4

      - name: JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mvn install

